### ISSUE TITLE
Django 2 support

### ISSUE THREAD

**Issue by daniellevinson** [auth0-samples/auth0-django-web-app#11]
Error when running db migrations:
```
$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/daniel/Documents/Workspaces/auth0-django-web-app/01-Login/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/Users/daniel/Documents/Workspaces/auth0-django-web-app/01-Login/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/daniel/Documents/Workspaces/auth0-django-web-app/01-Login/env/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/daniel/Documents/Workspaces/auth0-django-web-app/01-Login/env/lib/python3.6/site-packages/django/core/management/base.py", line 332, in execute
    self.check()
  File "/Users/daniel/Documents/Workspaces/auth0-django-web-app/01-Login/env/lib/python3.6/site-packages/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/daniel/Documents/Workspaces/auth0-django-web-app/01-Login/env/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 58, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/Users/daniel/Documents/Workspaces/auth0-django-web-app/01-Login/env/lib/python3.6/site-packages/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/daniel/Documents/Workspaces/auth0-django-web-app/01-Login/env/lib/python3.6/site-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/daniel/Documents/Workspaces/auth0-django-web-app/01-Login/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/Users/daniel/Documents/Workspaces/auth0-django-web-app/01-Login/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/Users/daniel/Documents/Workspaces/auth0-django-web-app/01-Login/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 397, in check
    for pattern in self.url_patterns:
  File "/Users/daniel/Documents/Workspaces/auth0-django-web-app/01-Login/env/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/daniel/Documents/Workspaces/auth0-django-web-app/01-Login/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/daniel/Documents/Workspaces/auth0-django-web-app/01-Login/env/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/daniel/Documents/Workspaces/auth0-django-web-app/01-Login/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/daniel/Documents/Workspaces/auth0-django-web-app/01-Login/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/daniel/Documents/Workspaces/auth0-django-web-app/01-Login/webappexample/urls.py", line 21, in <module>
    url(r'^', include('auth0login.urls'))
  File "/Users/daniel/Documents/Workspaces/auth0-django-web-app/01-Login/env/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/Users/daniel/Documents/Workspaces/auth0-django-web-app/01-Login/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/daniel/Documents/Workspaces/auth0-django-web-app/01-Login/auth0login/urls.py", line 7, in <module>
    url(r'^', include('django.contrib.auth.urls', namespace='auth')),
  File "/Users/daniel/Documents/Workspaces/auth0-django-web-app/01-Login/env/lib/python3.6/site-packages/django/urls/conf.py", line 39, in include
    'Specifying a namespace in include() without providing an app_name '
django.core.exceptions.ImproperlyConfigured: Specifying a namespace in include() without providing an app_name is not supported. Set the app_name attribute in the included module, or pass a 2-tuple containing the list of patterns and app_name instead.
```

Works fine with 1.9, so either lock the version on the requirements file or add support for 2.0.

**Comment by aaguiarz** [comment]
We are not supporting 2.0 yet, so well lock the version on requirements.

**Comment by albertoperdomo** [comment]
See https://github.com/auth0-samples/auth0-django-web-app/pull/19.
Official Quickstart and sample will be updated in the coming days.
